name: Staging

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  version-bump:
    name: 'Version bump'
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          commit-message: 'version bump to {{version}} [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
          
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  deployment:
    name: Deployment
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    needs: version-bump
    uses: ./.github/workflows/deployment.yml
    with:
      AWS_ROLE_ARN: arn:aws:iam::204115048155:role/OrganizationAccountAccessRole
      ENV_NAME: staging
    secrets: inherit